version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.13.0
    container_name: elk-elasticsearch-server
    environment:
      - "cluster.name=elasticsearch" #设置集群名称为elasticsearch
      - "discovery.type=single-node" #以单一节点模式启动
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" #设置使用jvm内存大小
    volumes:
      - ${ELK_BASE_DIR}/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins #插件文件挂载
      - ${ELK_BASE_DIR}/elk/elasticsearch/data:/usr/share/elasticsearch/data #数据文件挂载
    ports:
      - 9200:9200
  kibana:
    image: kibana:7.13.0
    container_name: elk-kibana-server
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    environment:
      - "elasticsearch.hosts=http://es:9200" #设置访问elasticsearch的地址
    ports:
      - 5601:5601
  logstash:
    image: logstash:7.13.0
    container_name: elk-logstash-server
    volumes:
      - ${ELK_BASE_DIR}/elk/logstash/conf:/usr/share/logstash/pipeline/ #挂载logstash的配置文件
    depends_on:
      - elasticsearch #kibana在elasticsearch启动之后再启动
    links:
      - elasticsearch:es #可以用es这个域名访问elasticsearch服务
    ports:
      - 4560:4560